### PR TITLE
Improve handling of services

### PR DESCRIPTION
**Pull request by jhart-r7**
This updates the handling of services such that you can now display much more than previously.  Previously, the only service known about was `NODE_NETWORK` and all others were unknown/ignored.  This PR:

* Adds several additional service names (from https://github.com/bitcoin/bitcoin/blob/master/src/protocol.h#L246-L278)
* Moves the `_services_to_text` helper to a place where it can be used by all

As an example, this simple client:

```
#!/usr/bin/env python

import socket
import sys
from protocoin.clients import BitcoinClient
from protocoin.exceptions import NodeDisconnectException
import protocoin.util

class MyBitcoinClient(BitcoinClient):
    def handle_version(self, message_header, message):
        print "services=%s" % protocoin.util.services_to_text(message.services)
        print "addr_from_services=%s" % protocoin.util.services_to_text(message.addr_from.services)
        print "addr_recv_services=%s" % protocoin.util.services_to_text(message.addr_recv.services)
        raise NodeDisconnectException

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((sys.argv[1], 8333))

try:
    client = MyBitcoinClient(sock)
    client.handshake()
    client.loop()
except NodeDisconnectException:
    pass
```

When run  as per the other examples:

```
(venv) $  python ./test_client.py bitcoin.sipa.be                                                                             
services=['NODE_BLOOM', 'NODE_WITNESS', 'NODE_NETWORK']
addr_from_services=['NODE_BLOOM', 'NODE_WITNESS', 'NODE_NETWORK']
addr_recv_services=[]
```

Run against a variety of other nodes, we see things like `addr_from_services=['NODE_BLOOM', 'NODE_BITCOIN_CASH', 'NODE_XTHIN', 'NODE_NETWORK']`, etc.

We can see that we now get some of the friendly service names plus the names of some I didn't define yet.

### CODE REVIEW

**Comment by perone** [comment]
Thanks for the PR ! Let me know when the PR is ready to be merged, I see that you are still adding some commits.

**Comment by jhart-r7** [comment]
@perone it should be ready for a review and merge now.  Thanks!

**Comment by perone** [comment]
Please add a description of the change in the changelog (you can add a new v.0.3 section there). Thanks again !

**Comment by perone** [comment]
Tahnks !! Will merge it !

**Comment by jhart-r7** [comment]
@perone thanks for landing! Hopefully folks find value in the new release.

**Pull request merged**
